# Generated by Django 3.2.5 on 2021-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='title',
            field=models.CharField(blank=True, choices=[('Spa', 'Spa'), ('Outdoor restaurant', 'Outdoor restaurant'), ('Poolside bar', 'Poolside bar'), ('Car parking', 'Car parking'), ('Swimming pool', 'Swimming pool')], max_length=20, null=True),
        ),
    ]
