# Generated by Django 3.2.5 on 2021-07-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_facilities_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_rooms',
            name='type',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=15, null=True),
        ),
    ]
